スタッフの追加、及び関連書籍の追加
vrcunity/vrcunity.github.io pull request #3
Opened 2021-03-19 13:50 UTC by Nazell2059

2021-03-19 18:20 UTC, slord399 requested changes
名前の表記について該当箇所にコメントしました。

2021-03-19 18:20 UTC, slord399 commented on docs/index.md
> +スタッフ：[Nazell](https://twitter.com/nazeru2)、[IKEA/Istria](https://twitter.com/IKEA_ToS)、[エスニヤ（うか）](https://twitter.com/y_esnya)、[GlinT](https://twitter.com/GlinTFraulein)、[meron](https://twitter.com/m
たぶんTony L.H. URAHAMAと書いてもVRChat民には誰？となるのでTony_Lewisでここに書く分にはどうでしょう？
(というよりVRChat ID表記の方が皆分かりやすいかも？)

2021-03-19 19:05 UTC, Nazell2059 commented on docs/index.md
> +スタッフ：[Nazell](https://twitter.com/nazeru2)、[IKEA/Istria](https://twitter.com/IKEA_ToS)、[エスニヤ（うか）](https://twitter.com/y_esnya)、[GlinT](https://twitter.com/GlinTFraulein)、[meron](https://twitter.com/m
Tony_Lewisの方へ表記変更しました。

2021-03-19 19:12 UTC, slord399 approved these changes
私の方はこれでいいかと。

2021-03-20 10:40 UTC, esnya approved these changes
ついでに私のDisplayNameも更新していただけると嬉しいです

2021-03-20 10:53 UTC, meronmks reviewed
名前のところに少しコメントしています。

2021-03-20 10:53 UTC, meronmks commented on docs/index.md
> +スタッフ：[Nazell](https://twitter.com/nazeru2)、[IKEA/Istria](https://twitter.com/IKEA_ToS)、[エスニヤ（うか）](https://twitter.com/y_esnya)、[GlinT](https://twitter.com/GlinTFraulein)、[meron](https://twitter.com/m
既にほかでも意見がありましたが、VRChat ID表記に合わせてしまうのであれば『meronmks / めろん』の方にしてもらえると助かります。（パッと見そんな変わらないのでまあどっちでもOKではありますが）

2021-03-27 03:14 UTC, Nazell2059 commented on docs/index.md
> +スタッフ：[Nazell](https://twitter.com/nazeru2)、[IKEA/Istria](https://twitter.com/IKEA_ToS)、[エスニヤ（うか）](https://twitter.com/y_esnya)、[GlinT](https://twitter.com/GlinTFraulein)、[meron](https://twitter.com/m
お二方のお名前をVRC準拠に変更しました。

2021-03-27 10:54 UTC, esnya approved these changes

2021-04-01 00:45 UTC, meronmks approved these changes

2021-04-01 06:04 UTC, esnya approved these changes

2021-04-01 06:53 UTC, slord399 approved these changes

2021-04-10 05:22 UTC, meronmks commented
問題なさそうとみんな回答しておきながらマージせず放置状態なのでマージします。

2021-04-10 05:22 UTC, merged